const sampleData = {
    apartment_id:'01', 
    apartment_date:'06/25/2022', 
    apartment_name: 'Emory Point',
    apartment_unit: '260',
    apartment_rent: '2835',
    apartment_deposit: '750',
    apartment_lease: '12',
    apartment_bed: '2',
    apartment_bath: '2',
    apartment_sqft: '1050',
    apartment_movein: '08/02/2022',
    apartment_pet: false,
    apartment_url: 'https://www.apartments.com/the-grand-at-bayfront-hercules-ca/bgcq66b/',
    location_id: '01',
    location_city: 'Hercules',
    location_state: 'CA',
    location_zipcode: 94547,
    location_address: '2200 John Muir Pky',
    apartment_contact: '(650) 523-0047',
    features_id: '01',
    features_floor: 'Hardwood',
    features_dishwasher: null,
    features_ac: true,
    features_patio: null,
    features_balcony: true,
    features_pool: true,
    features_gym: true,
};

export default sampleData;